### ISSUE TITLE
Tweaks needed by modules

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/TeraMath#24]
Going through the remainder of compile errors I can find in my mega-workspace after https://github.com/MovingBlocks/Terasology/pull/1417 was merged

Found:

- [x] Rails used Vector3f.negate() and .interpolate() in MoveDescriptor - I commented out and left a todo. Need to either add the methods or find a replacement?
- [x] Rails also uses .negate() in MinecartAction
- [x] Rails uses `QuaternionUtil.setEuler(yawPitch,...` in MinecartSystem.java and a few similar hits from TeraBullet which uses vecmath :-( Should we just convert it on the spot there? TeraBullet could be a beast to convert when we are thinking about replacing it some day. Class also uses .negate().
- [x] ItemRendering uses .interpolate() in AnimateRotationClientSystem
- [x] CustomOreGen's AbstractMultiChunkStructureDefinition uses Vector3i.clone() which probably had a version in vecmath? Now it inherits from Object and complains. I changed to a `new` object instantiation but review would be good (or maybe add a new clone method)
- [x] TutorialWorldGeneration does the same in HouseRasterizer
- [x] Pathfinding uses float in HAStar on Vector3i.length() which is now double in TeraMath. I added a cast but I dunno if that matters?
- [x] Miniion uses AxisAngle4f in RevisedSimpleMinionAISystem - which we don't have in TeraMath? Do we need it? Miniion is pretty old and its code might be trying to do obsolete things

I found some more places where Vecmath is still in use, yet in ways that are compatible, so those places don't get flagged as compile errors. Includes 39 hits in engine but maybe that's included on the future todo list?

I fixed a bunch of remaining non-issues where swapping to the new class allowed compilation to succeed :-)

Tested around and we might have a few new errors here and there to look at more. Deer doesn't move anywhere yet, maybe related to position calcs in Pathfinding

**Comment by Cervator** [comment]
Oh, and grabbing the note from GrowingFlora just for reference so we have it in an open issue

@msteiger - Note to myself: a few more Matrix4f constructors wouldn't hurt though

**Comment by msteiger** [comment]
All issues should be fixed now - not sure the deer wouldn't move though.

**Comment by Cervator** [comment]
Thanks for the quick and thorough response - all better now :-)

Took some thorough workspace cleaning to get fully up to speed, but even the deer works now, yay!
